sudo: required
language: go

go:
  - 1.5.4
  - 1.6.3
  - 1.7.1
  - tip

cache:
  directories:
    - vendor
    - ${HOME}/.glide

before_install:
  - curl https://glide.sh/get | sh

install:
  - export GO15VENDOREXPERIMENT=1
  - make install

script:
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash) -f coverage.txt
