sudo: required
language: go

services:
  - docker

go:
  - 1.5.4
  - 1.6.3
  - 1.7.1
  - tip

cache:
  directories:
    - vendor
    - ${HOME}/.glide

before_install:
  - mkdir -p $GOPATH/bin
  - curl https://glide.sh/get | sh

install:
  - export GO15VENDOREXPERIMENT=1
  - make install

script:
  - make test
  - make docker

after_success:
  - bash <(curl -s https://codecov.io/bash) -f coverage.txt
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_GO_VERSION" == "1.7.1" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    make docker_deploy tag=latest;
    fi
